server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: root
  jpa:
    hibernate:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        show_sql: true

